---
- name: Create a VIP, pool, pool members and nodes
  hosts: testf5
  connection: local
  tasks:
## create a pool first
   - name: Create a pool
     bigip_pool:
      state: "present"
      partition: "Common"
      lb_method: "round_robin"
      name: "VIP_2_Pool"
      user: "admin"
      server: "MMI-DC01-LAB-TEST2.mmi.mig.corp"
      password: "mig!uj@cmh"
      validate_certs: "no"
     delegate_to: localhost
## create nodes
   - name: create node1
     bigip_node: 
      host: "100.100.100.100"
      name: "node_1"
      server: "MMI-DC01-LAB-TEST2.mmi.mig.corp"
      user: "admin"
      password: "mig!uj@cmh"
      validate_certs: "no"
     delegate_to: localhost 
     
   - name: create node2
     bigip_node: 
      host: "100.100.100.101"
      name: "node_2"
      user: "admin"
      server: "MMI-DC01-LAB-TEST2.mmi.mig.corp"
      password: "mig!uj@cmh"
      validate_certs: "no"
     delegate_to: localhost  
     
##  Add nodes to pool 
   - name: Add nodes to pool
     bigip_pool_member:
      description: "VIP_2_Pool_members"
      host: "{{ item.host }}"
      name: "{{ item.name }}"
      port: 80
      pool: "VIP_2_Pool"
      user: "admin"
      server: "MMI-DC01-LAB-TEST2.mmi.mig.corp"
      password: "mig!uj@cmh"
      validate_certs: "no"
     delegate_to: localhost
     with_items:
     - host: "100.100.100.100"
       name: "node_1"
     - host: "100.100.100.101"
       name: "node_2"
   
## Create and add pool to VIP
   - name: create a VIP
     bigip_virtual_server:
      description: "foo-vip"
      destination: "172.16.10.109"
      name: "vip-2"
      port: "443"
      pool: "VIP_2_Pool"
      server: MMI-DC01-LAB-TEST2.mmi.mig.corp
      snat: "Automap"
      user: "admin"
      password: "mig!uj@cmh"
      all_profiles:
       - "http"
       - "clientssl"
      validate_certs: "no"  
     delegate_to: localhost
